server:
  port: 8012

spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hwajin15/Configuration.git
      
          clone-on-start: true

#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh
